spring:
  security:
    oauth2:
      resource-server:
          jwt:
              issuer-uri: http://127.0.0.1:8080/realms/construcao-sw
              jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
    port: 8081

#
#jwt:
#  auth:
#    converter:
#      resource-id: constrsw-2023-2
#      principal-attribute: admin@pucrs.br